{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMtZ8V6pWJM1MMOor8pwpQ0",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Samin-Sadaf7/Image_works/blob/main/Targeted_Physical_World_Attention_Attack_on_Deep_Learning_Models_in_Road_Sign_Recognition.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "iLs3niVIy3-3",
        "outputId": "79204321-0bf5-4d25-def9-f9b425a595af"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Cloning into 'TAA-IoT-J'...\n",
            "remote: Enumerating objects: 7753, done.\u001b[K\n",
            "remote: Counting objects: 100% (47/47), done.\u001b[K\n",
            "remote: Compressing objects: 100% (43/43), done.\u001b[K\n",
            "remote: Total 7753 (delta 14), reused 0 (delta 0), pack-reused 7706\u001b[K\n",
            "Receiving objects: 100% (7753/7753), 25.47 MiB | 12.97 MiB/s, done.\n",
            "Resolving deltas: 100% (42/42), done.\n",
            "Updating files: 100% (22620/22620), done.\n"
          ]
        }
      ],
      "source": [
        "#clone a git repo\n",
        "!git clone https://github.com/AdvAttack/TAA-IoT-J.git"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%cd /content/TAA-IoT-J/TAA-optimization/\n",
        "%rm -f Pipfile"
      ],
      "metadata": {
        "id": "if9OgoeP0cdJ"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install pipenv\n",
        "!pipenv install tensorflow==1.4.1\n",
        "!pipenv install keras==1.2.0\n",
        "!pipenv install scipy\n",
        "!pipenv install opencv-python\n",
        "!pipenv install pillow\n",
        "!pipenv shell"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "wqjm0OlozCmK",
        "outputId": "b4c9a87c-c3fc-407e-a634-bcfc589d3d94"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: pipenv in /usr/local/lib/python3.10/dist-packages (2024.0.1)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pipenv) (2024.6.2)\n",
            "Requirement already satisfied: setuptools>=67 in /usr/local/lib/python3.10/dist-packages (from pipenv) (67.7.2)\n",
            "Requirement already satisfied: virtualenv>=20.24.2 in /usr/local/lib/python3.10/dist-packages (from pipenv) (20.26.3)\n",
            "Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.24.2->pipenv) (0.3.8)\n",
            "Requirement already satisfied: filelock<4,>=3.12.2 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.24.2->pipenv) (3.15.4)\n",
            "Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.24.2->pipenv) (4.2.2)\n",
            "\u001b[1mCreating a virtualenv for this project...\u001b[0m\n",
            "Pipfile: \u001b[33m\u001b[1m/content/TAA-IoT-J/TAA-optimization/Pipfile\u001b[0m\n",
            "\u001b[1mUsing default python from\u001b[0m \u001b[33m\u001b[1m/usr/bin/python3\u001b[0m \u001b[32m(3.10.12)\u001b[0m \u001b[1mto create virtualenv...\u001b[0m\n",
            "\u001b[2K\u001b[32m⠸\u001b[0m Creating virtual environment...\u001b[36mcreated virtual environment CPython3.10.12.final.0-64 in 225ms\n",
            "  creator CPython3Posix(dest=/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O, clear=False, no_vcs_ignore=False, global=False)\n",
            "  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)\n",
            "    added seed packages: pip==24.1, setuptools==70.1.0, wheel==0.43.0\n",
            "  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator\n",
            "\u001b[0m\n",
            "✔ Successfully created virtual environment!\n",
            "\u001b[2K\u001b[32m⠸\u001b[0m Creating virtual environment...\n",
            "\u001b[1A\u001b[2K\u001b[32mVirtualenv location: /root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O\u001b[0m\n",
            "\u001b[1mCreating a Pipfile for this project\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1;32mInstalling \u001b[0m\u001b[1;33mtensorflow\u001b[0m\u001b[1;32m==\u001b[0m\u001b[1;36m1.4\u001b[0m\u001b[1;32m.\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[?25lResolving \u001b[33mtensorflow\u001b[0m==\u001b[1;36m1.4\u001b[0m.\u001b[1;36m1\u001b[0m\u001b[33m...\u001b[0m\n",
            "\u001b[2K\u001b[1mAdded \u001b[0m\u001b[1;32mtensorflow\u001b[0m to Pipfile's \u001b[1;33m[\u001b[0m\u001b[33mpackages\u001b[0m\u001b[1;33m]\u001b[0m \u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Installation Succeeded\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Installing tensorflow...\n",
            "\u001b[1A\u001b[2K\u001b[1mPipfile.lock not found, creating\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "Locking\u001b[0m \u001b[33m[packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[?25lBuilding requirements\u001b[33m...\u001b[0m\n",
            "\u001b[2KResolving dependencies\u001b[33m...\u001b[0m\n",
            "\u001b[2K✘ Locking Failed!\n",
            "\u001b[32m⠧\u001b[0m Locking packages...False\n",
            "CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement tensorflow==1.4.1 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.0.post1, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1)\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py\", line 645, in _main\n",
            "[ResolutionFailure]:       resolve_packages(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py\", line 612, in resolve_packages\n",
            "[ResolutionFailure]:       results, resolver = resolve(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py\", line 592, in resolve\n",
            "[ResolutionFailure]:       return resolve_deps(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 932, in resolve_deps\n",
            "[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 700, in actually_resolve_deps\n",
            "[ResolutionFailure]:       resolver.resolve()\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 457, in resolve\n",
            "[ResolutionFailure]:       raise ResolutionFailure(message=str(e))\n",
            "[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.\n",
            "  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.\n",
            "  Hint: try $ pipenv lock --pre if it is a pre-release dependency.\n",
            "ERROR: No matching distribution found for tensorflow==1.4.1\n",
            "\n",
            "\u001b[2K\u001b[32m⠧\u001b[0m Locking packages...\n",
            "\u001b[1A\u001b[2KTraceback (most recent call last):\n",
            "  File \"/usr/local/bin/pipenv\", line 8, in <module>\n",
            "    sys.exit(cli())\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1157, in __call__\n",
            "    return self.main(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/cli/options.py\", line 58, in main\n",
            "    return super().main(*args, **kwargs, windows_expand_args=False)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1078, in main\n",
            "    rv = self.invoke(ctx)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1688, in invoke\n",
            "    return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1434, in invoke\n",
            "    return ctx.invoke(self.callback, **ctx.params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 783, in invoke\n",
            "    return __callback(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/decorators.py\", line 92, in new_func\n",
            "    return ctx.invoke(f, obj, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 783, in invoke\n",
            "    return __callback(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/cli/command.py\", line 209, in install\n",
            "    do_install(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/install.py\", line 234, in do_install\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/install.py\", line 209, in do_install\n",
            "    do_init(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/install.py\", line 653, in do_init\n",
            "    do_lock(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/lock.py\", line 66, in do_lock\n",
            "    venv_resolve_deps(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 873, in venv_resolve_deps\n",
            "    c = resolve(cmd, st, project=project)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 737, in resolve\n",
            "    raise RuntimeError(\"Failed to lock Pipfile.lock!\")\n",
            "RuntimeError: Failed to lock Pipfile.lock!\n",
            "\u001b[1;32mInstalling \u001b[0m\u001b[1;33mkeras\u001b[0m\u001b[1;32m==\u001b[0m\u001b[1;36m1.2\u001b[0m\u001b[1;32m.\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[?25lResolving \u001b[33mkeras\u001b[0m==\u001b[1;36m1.2\u001b[0m.\u001b[1;36m0\u001b[0m\u001b[33m...\u001b[0m\n",
            "\u001b[2K\u001b[1mAdded \u001b[0m\u001b[1;32mkeras\u001b[0m to Pipfile's \u001b[1;33m[\u001b[0m\u001b[33mpackages\u001b[0m\u001b[1;33m]\u001b[0m \u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Installation Succeeded\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Installing keras...\n",
            "\u001b[1A\u001b[2K\u001b[1mPipfile.lock not found, creating\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "Locking\u001b[0m \u001b[33m[packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[?25lBuilding requirements\u001b[33m...\u001b[0m\n",
            "\u001b[2KResolving dependencies\u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Success!\n",
            "\u001b[2K\u001b[32m⠙\u001b[0m Locking packages...\n",
            "\u001b[1A\u001b[2KLocking\u001b[0m \u001b[33m[dev-packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[1mUpdated Pipfile.lock (6094f852b803a180f659f7d2220da954420bdc26d40790eef77ce48c3612f304)!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1m12f304\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1;32mInstalling scipy\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[?25lResolving scipy\u001b[33m...\u001b[0m\n",
            "\u001b[2K\u001b[1mAdded \u001b[0m\u001b[1;32mscipy\u001b[0m to Pipfile's \u001b[1;33m[\u001b[0m\u001b[33mpackages\u001b[0m\u001b[1;33m]\u001b[0m \u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Installation Succeeded\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Installing scipy...\n",
            "\u001b[1A\u001b[2K\u001b[1;33mPipfile.lock \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m12f304\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m out of date: run `pipfile lock` to update to \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m56983a\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1mRunning\u001b[0m \u001b[33m\u001b[1m$ pipenv lock\u001b[0m \u001b[1mthen\u001b[0m \u001b[33m\u001b[1m$ pipenv sync\u001b[0m\u001b[1m.\u001b[0m\n",
            "Locking\u001b[0m \u001b[33m[packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[?25lBuilding requirements\u001b[33m...\u001b[0m\n",
            "\u001b[2KResolving dependencies\u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Success!\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Locking packages...\n",
            "\u001b[1A\u001b[2KLocking\u001b[0m \u001b[33m[dev-packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[1mUpdated Pipfile.lock (760f74f8954264a34e7cb3651370dddd81eb7a2034e63f1373656df2de56983a)!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1m56983a\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[32mAll dependencies are now up-to-date!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1m56983a\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1;32mInstalling opencv-python\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[?25lResolving opencv-python\u001b[33m...\u001b[0m\n",
            "\u001b[2K\u001b[1mAdded \u001b[0m\u001b[1;32mopencv-python\u001b[0m to Pipfile's \u001b[1;33m[\u001b[0m\u001b[33mpackages\u001b[0m\u001b[1;33m]\u001b[0m \u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Installation Succeeded\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Installing opencv-python...\n",
            "\u001b[1A\u001b[2K\u001b[1;33mPipfile.lock \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m56983a\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m out of date: run `pipfile lock` to update to \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m959762\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1mRunning\u001b[0m \u001b[33m\u001b[1m$ pipenv lock\u001b[0m \u001b[1mthen\u001b[0m \u001b[33m\u001b[1m$ pipenv sync\u001b[0m\u001b[1m.\u001b[0m\n",
            "Locking\u001b[0m \u001b[33m[packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[?25lBuilding requirements\u001b[33m...\u001b[0m\n",
            "\u001b[2KResolving dependencies\u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Success!\n",
            "\u001b[2K\u001b[32m⠹\u001b[0m Locking packages...\n",
            "\u001b[1A\u001b[2KLocking\u001b[0m \u001b[33m[dev-packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[1mUpdated Pipfile.lock (d7416046adb83685e32ce83bbf5ab50e848b626002fa80237d363377f8959762)!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1;36m959762\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[32mAll dependencies are now up-to-date!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1;36m959762\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1;32mInstalling pillow\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[?25lResolving pillow\u001b[33m...\u001b[0m\n",
            "\u001b[2K\u001b[1mAdded \u001b[0m\u001b[1;32mpillow\u001b[0m to Pipfile's \u001b[1;33m[\u001b[0m\u001b[33mpackages\u001b[0m\u001b[1;33m]\u001b[0m \u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Installation Succeeded\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Installing pillow...\n",
            "\u001b[1A\u001b[2K\u001b[1;33mPipfile.lock \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m959762\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m out of date: run `pipfile lock` to update to \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m953b46\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1mRunning\u001b[0m \u001b[33m\u001b[1m$ pipenv lock\u001b[0m \u001b[1mthen\u001b[0m \u001b[33m\u001b[1m$ pipenv sync\u001b[0m\u001b[1m.\u001b[0m\n",
            "Locking\u001b[0m \u001b[33m[packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[?25lBuilding requirements\u001b[33m...\u001b[0m\n",
            "\u001b[2KResolving dependencies\u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Success!\n",
            "\u001b[2K\u001b[32m⠦\u001b[0m Locking packages...\n",
            "\u001b[1A\u001b[2KLocking\u001b[0m \u001b[33m[dev-packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[1mUpdated Pipfile.lock (ad64c5969089337ae672fdd3f4f636a697043bec2bff7f485f62e3ea62953b46)!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1m953b46\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[32mAll dependencies are now up-to-date!\u001b[0m\n",
            "To activate this project's virtualenv, run \u001b[33mpipenv shell\u001b[0m.\n",
            "Alternatively, run a command inside the virtualenv with \u001b[33mpipenv run\u001b[0m.\n",
            "\u001b[1mInstalling dependencies from Pipfile.lock \u001b[0m\u001b[1m(\u001b[0m\u001b[1m953b46\u001b[0m\u001b[1m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "Launching subshell in virtual environment...\n",
            "\u001b[?2004h\u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m#  . /root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/bin/activate\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# sh Perturbation_optimization_Stop_SpeedLimit45.sh\n",
            "mkdir: cannot create directory ‘optimization_output/Attention’: File exists\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/gennoise_many_images26.py\", line 27\n",
            "    print \"going into setup\"\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# sh Perturbation_optimization_Stop_SpeedLimit45.sh\n",
            "mkdir: cannot create directory ‘optimization_output/Attention’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/noisy_images’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/model’: File exists\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/gennoise_many_images26.py\", line 1, in <module>\n",
            "    from utils26 import get_adv_target, load_norm_mask, setup_attack_graph, report_extreme_values, load_many_images, get_print_triplets\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/utils26.py\", line 118\n",
            "    print 'avg %s value'%name, np.average(arr_flat)\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# sh Perturbation_optimization_Stop_SpeedLimit45.sh\n",
            "mkdir: cannot create directory ‘optimization_output/Attention’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/noisy_images’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/model’: File exists\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/gennoise_many_images26.py\", line 1, in <module>\n",
            "    from utils26 import get_adv_target, load_norm_mask, setup_attack_graph, report_extreme_values, load_many_images, get_print_triplets\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/utils26.py\", line 118\n",
            "    print 'avg %s value'%name, np.average(arr_flat)\n",
            "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# sh Perturbation_optimization_Stop_SpeedLimit45.sh\n",
            "mkdir: cannot create directory ‘optimization_output/Attention’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/noisy_images’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/model’: File exists\n",
            "Using TensorFlow backend.\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/gennoise_many_images26.py\", line 1, in <module>\n",
            "    from utils26 import get_adv_target, load_norm_mask, setup_attack_graph, report_extreme_values, load_many_images, get_print_triplets\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/utils26.py\", line 2, in <module>\n",
            "    import keras\n",
            "  File \"/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/lib/python3.10/site-packages/keras/__init__.py\", line 2, in <module>\n",
            "    from . import backend\n",
            "  File \"/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/lib/python3.10/site-packages/keras/backend/__init__.py\", line 67, in <module>\n",
            "    from .tensorflow_backend import *\n",
            "  File \"/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/lib/python3.10/site-packages/keras/backend/tensorflow_backend.py\", line 1, in <module>\n",
            "    import tensorflow as tf\n",
            "ModuleNotFoundError: No module named 'tensorflow'\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# pipenv install tensorflow==1.4.1\n",
            "\u001b[1;32mInstalling \u001b[0m\u001b[1;33mtensorflow\u001b[0m\u001b[1;32m==\u001b[0m\u001b[1;36m1.4\u001b[0m\u001b[1;32m.\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[?25lResolving \u001b[33mtensorflow\u001b[0m==\u001b[1;36m1.4\u001b[0m.\u001b[1;36m1\u001b[0m\u001b[33m...\u001b[0m\n",
            "\u001b[2K\u001b[1mAdded \u001b[0m\u001b[1;32mtensorflow\u001b[0m to Pipfile's \u001b[1;33m[\u001b[0m\u001b[33mpackages\u001b[0m\u001b[1;33m]\u001b[0m \u001b[33m...\u001b[0m\n",
            "\u001b[2K✔ Installation Succeeded\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Installing tensorflow...\n",
            "\u001b[1A\u001b[2K\u001b[1;33mPipfile.lock \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m953b46\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m out of date: run `pipfile lock` to update to \u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33md770d2\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m...\u001b[0m\n",
            "\u001b[1mRunning\u001b[0m \u001b[33m\u001b[1m$ pipenv lock\u001b[0m \u001b[1mthen\u001b[0m \u001b[33m\u001b[1m$ pipenv sync\u001b[0m\u001b[1m.\u001b[0m\n",
            "Locking\u001b[0m \u001b[33m[packages]\u001b[0m dependencies...\u001b[0m\n",
            "\u001b[?25lBuilding requirements\u001b[33m...\u001b[0m\n",
            "\u001b[2KResolving dependencies\u001b[33m...\u001b[0m\n",
            "\u001b[2K✘ Locking Failed!\n",
            "\u001b[32m⠋\u001b[0m Locking packages...False\n",
            "CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement tensorflow==1.4.1 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.0.post1, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1)\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py\", line 645, in _main\n",
            "[ResolutionFailure]:       resolve_packages(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py\", line 612, in resolve_packages\n",
            "[ResolutionFailure]:       results, resolver = resolve(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/resolver.py\", line 592, in resolve\n",
            "[ResolutionFailure]:       return resolve_deps(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 932, in resolve_deps\n",
            "[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 700, in actually_resolve_deps\n",
            "[ResolutionFailure]:       resolver.resolve()\n",
            "[ResolutionFailure]:   File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 457, in resolve\n",
            "[ResolutionFailure]:       raise ResolutionFailure(message=str(e))\n",
            "[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.\n",
            "  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.\n",
            "  Hint: try $ pipenv lock --pre if it is a pre-release dependency.\n",
            "ERROR: No matching distribution found for tensorflow==1.4.1\n",
            "\n",
            "\u001b[2K\u001b[32m⠋\u001b[0m Locking packages...\n",
            "\u001b[1A\u001b[2KTraceback (most recent call last):\n",
            "  File \"/usr/local/bin/pipenv\", line 8, in <module>\n",
            "    sys.exit(cli())\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1157, in __call__\n",
            "    return self.main(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/cli/options.py\", line 58, in main\n",
            "    return super().main(*args, **kwargs, windows_expand_args=False)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1078, in main\n",
            "    rv = self.invoke(ctx)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1688, in invoke\n",
            "    return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 1434, in invoke\n",
            "    return ctx.invoke(self.callback, **ctx.params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 783, in invoke\n",
            "    return __callback(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/decorators.py\", line 92, in new_func\n",
            "    return ctx.invoke(f, obj, *args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py\", line 783, in invoke\n",
            "    return __callback(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/cli/command.py\", line 209, in install\n",
            "    do_install(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/install.py\", line 234, in do_install\n",
            "    raise e\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/install.py\", line 209, in do_install\n",
            "    do_init(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/install.py\", line 624, in do_init\n",
            "    do_update(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/update.py\", line 61, in do_update\n",
            "    do_lock(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/routines/lock.py\", line 66, in do_lock\n",
            "    venv_resolve_deps(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 873, in venv_resolve_deps\n",
            "    c = resolve(cmd, st, project=project)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/pipenv/utils/resolver.py\", line 737, in resolve\n",
            "    raise RuntimeError(\"Failed to lock Pipfile.lock!\")\n",
            "RuntimeError: Failed to lock Pipfile.lock!\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# sh Perturbation_optimization_Stop_SpeedLimit45.sh\n",
            "mkdir: cannot create directory ‘optimization_output/Attention’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/noisy_images’: File exists\n",
            "mkdir: cannot create directory ‘optimization_output/Attention/model’: File exists\n",
            "Using TensorFlow backend.\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/gennoise_many_images26.py\", line 1, in <module>\n",
            "    from utils26 import get_adv_target, load_norm_mask, setup_attack_graph, report_extreme_values, load_many_images, get_print_triplets\n",
            "  File \"/content/TAA-IoT-J/TAA-optimization/utils26.py\", line 2, in <module>\n",
            "    import keras\n",
            "  File \"/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/lib/python3.10/site-packages/keras/__init__.py\", line 2, in <module>\n",
            "    from . import backend\n",
            "  File \"/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/lib/python3.10/site-packages/keras/backend/__init__.py\", line 67, in <module>\n",
            "    from .tensorflow_backend import *\n",
            "  File \"/root/.local/share/virtualenvs/TAA-optimization-A7zdvV3O/lib/python3.10/site-packages/keras/backend/tensorflow_backend.py\", line 1, in <module>\n",
            "    import tensorflow as tf\n",
            "ModuleNotFoundError: No module named 'tensorflow'\n",
            "\u001b[?2004h(TAA-optimization) \u001b[01;34m/content/TAA-IoT-J/TAA-optimization\u001b[00m# \n",
            "Aborted!\n",
            "^C\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "vIRNWVXDzQNX"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}